### ISSUE TITLE
Get a decent logo and themes

### ISSUE THREAD

**Issue by Jldevictoria** [Jldevictoria/Oldentide#48]
The poop dragon has been around long enough, its time to make a nice beautiful logo that can be used with some decent looking themes.

Some things I like, and might be interested in:

- One icon
- One full name text
- Accent pieces like borders and a color scheme.

Color schemes I think would be cool:

- [First](http://paletton.com/palette.php?uid=10n0u0kahg95n4M3Zavh9mugYmL) 
![image](https://user-images.githubusercontent.com/6485853/29738741-cac7f786-89e0-11e7-91df-685d522307ec.png)

- [Second](http://paletton.com/palette.php?uid=10K0u0kbxbebM4S4u4tkfjKjUjR) 
![image](https://user-images.githubusercontent.com/6485853/29738743-f7783c6e-89e0-11e7-8679-aed0be13a247.png)

I like the idea of using chains, wood, metal, swords, daggers etc...

**Comment by Jldevictoria** [comment]
Got the logo started... need to figure out something to add in the middle... thinking about a dagger... or a skull... maybe with a ruby somewhere in there.
![image](https://user-images.githubusercontent.com/6485853/29858830-214d48c8-8d14-11e7-9d9d-34286689a4fd.png)

**Comment by davidlukerice** [comment]
Nice! yah, some kind of silver emblem could be cool. Or coat of arms (ex: https://i.pinimg.com/originals/63/38/d5/6338d5f8b8d55fce0f427f7118bf4ad0.jpg) somehow integrating lore/rubies into the various figures

**Comment by Jldevictoria** [comment]
Tentatively using this as a logo:

![image](https://user-images.githubusercontent.com/6485853/54056734-d5917600-41a5-11e9-897b-d8f181fee650.png)

**Comment by Jldevictoria** [comment]
Updating to this, I like it better:

![image](https://user-images.githubusercontent.com/6485853/54564639-85769880-4989-11e9-94bb-1e9c51bcf0a6.png)

**Comment by Jldevictoria** [comment]
I'm going to Mark this as closed.  I think the logo and themes are pretty clear from this issue's comments.

One thing is that I am playing to drop the full name icon.
